export const ADD_TO_CART='ADD_TO_CART';

export const UPDATE_CART='UPDATE_CART';

export const UPDATE_CART_WITH_CHECKOUT='UPDATE_CART_WITH_CHECKOUT';

export const REMOVE_TO_CART='REMOVE_TO_CART';

export const REMOVE_ALL_TO_CART='REMOVE_ALL_TO_CART';

